#! /bin/bash

appname=stanchion

. /etc/.docker_functions

stanchion_ip=${STANCHION_IP:-$(get_docker_container_nat_ip ${STANCHION_PORT:-8085})}
stanchion_port=${STANCHION_PORT:-$(get_docker_container_nat_port ${STANCHION_PORT:-8085})}
stanchion_name=${STANCHION_NAME:-stanchion}

serf tags -set stanchion_connect=${stanchion_ip}:${stanchion_port}

# Ensure correct ownership and permissions on volumes
#
chown stanchion:riak ${log_dir}
chmod 755 ${log_dir}

# Open file descriptor limit
#
ulimit -n 4096

# Ensure the Erlang node name is set correctly
#
sed -i.bak "s/-name .*/-name ${stanchion_name}@${stanchion_ip}:${stanchion_port}/" /etc/stanchion/vm.args
sed -i /etc/stanchion/app.config -e "s/stanchion_ip,.*/stanchion_ip, \"${stanchion_ip}\"},/"
sed -i /etc/stanchion/app.config -e "s/stanchion_port,.*/stanchion_port, ${stanchion_port}},/"

# Start Stanchion

exec /sbin/setuser stanchion "$(ls -d /usr/lib/stanchion/erts*)/bin/run_erl" "/tmp/stanchion" \
  "/var/log/stanchion" "exec /usr/sbin/stanchion console"

serf tags -del stanchion_connect
